SPRITE_SCALING_FOOD = 0.2

SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Genetic algorithm tests"

FOOD_COUNT = 50
window = None
SPRITE_SCALING_BACTERIA = 0.2
BACTERIA_COUNT = 10

BACTERIA_SPEED = 3

min_weight = 0.5
